build: off
cache:
  - '%APPDATA%\npm-cache'
clone_depth: 1
skip_branch_with_pr: true
skip_commits:
  files:
    - '**/*.md'
configuration:
  - FreshDeps
  - LockedDeps
environment:
  nodejs_version: "7.4.0"
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install --global npm@5.5.1
  - npm --version
  - if %configuration% == FreshDeps (npm install --no-shrinkwrap --prefer-online)
  - if %configuration% == LockedDeps (npm install --prefer-offline)
test_script:
  - npm run coverage
