environment:
  nodejs_version: "6.3.0"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node --version
  - npm --version
  - npm run coverage

# Don't actually build.
build: off
